#!/usr/bin/env python3
"""
wormhole_navigator.py  –  ROS 2 Humble
=======================================
Multi-map (multi-floor) navigation using wormhole logic ported from the
original ROS 1 `multi_map_nav` package (Multi-Map-Navigation repo).

Key differences from the ROS 1 original
-----------------------------------------
  • rclpy instead of rospy
  • Nav2 NavigateToPose action instead of move_base
  • /map_server/load_map service (Nav2 Lifecycle Map Server)
    instead of `rosrun map_server map_server` + system()
  • rclpy_action instead of actionlib
  • SQLite3 wormhole DB schema kept identical for compatibility

Elevator door virtual wall logic  (NEW – per user requirements)
---------------------------------------------------------------
Before the robot approaches an elevator:
  1. A virtual LINE barrier is drawn across the elevator door opening
     via nav2_virtual_layer AddLine service → robot cannot enter yet.
  2. The robot waits for /elevator_status to confirm the car has arrived
     and doors have opened.
  3. Only then is the virtual wall removed (RemoveShape) and the robot
     drives into the elevator.
  4. After the elevator reports arrival at the target floor, the map is
     hot-swapped and AMCL re-initialised at the exit position.

SDF2MAP compatibility
---------------------
Maps generated by SDF2MAP (https://github.com/sherif1152/SDF2MAP) use:
  - resolution: 0.05 m/px
  - origin: [x, y, 0.0]  (bottom-left in world coords)
  - occupied_thresh: 0.65 / free_thresh: 0.25
The wormhole DB stores the full path to each floor's generated YAML file.

Database schema (same as original repo)
----------------------------------------
  CREATE TABLE wormholes (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      from_map        TEXT NOT NULL,
      to_map          TEXT NOT NULL,
      from_x          REAL NOT NULL,
      from_y          REAL NOT NULL,
      from_yaw        REAL NOT NULL DEFAULT 0.0,
      map_yaml_path   TEXT NOT NULL,
      -- Elevator door endpoints for virtual wall:
      door_x1         REAL NOT NULL DEFAULT 0.0,
      door_y1         REAL NOT NULL DEFAULT 0.0,
      door_x2         REAL NOT NULL DEFAULT 0.0,
      door_y2         REAL NOT NULL DEFAULT 0.0,
      elevator_id     TEXT NOT NULL DEFAULT 'elevator_A'
  );

Usage
-----
  ros2 run hotel_luggage_robot wormhole_navigator.py \\
      --ros-args \\
      -p wormhole_db_path:=/path/to/hotel_wormholes.db \\
      -p initial_map:=floor_1 \\
      -p maps_base_dir:=/path/to/maps/

  # Seed demo database:
  python3 wormhole_navigator.py --seed-db /path/to/hotel.db /path/to/maps/
"""

import math
import sqlite3
import threading
import time
from typing import Optional, Tuple

import rclpy
from rclpy.action import ActionServer, CancelResponse, GoalResponse
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.executors import MultiThreadedExecutor
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy

from geometry_msgs.msg import PoseStamped, PoseWithCovarianceStamped
from nav2_msgs.action import NavigateToPose
from nav2_msgs.srv import LoadMap
from std_msgs.msg import String

import tf2_ros
from tf2_ros import TransformException

# nav2_virtual_layer services (from repo 1: nav2-virtual-layer)
try:
    from nav2_virtual_layer.srv import AddLine, RemoveShape
    _HAS_VIRTUAL_LAYER = True
except ImportError:
    _HAS_VIRTUAL_LAYER = False

# ── If the hotel_luggage_robot message package is not yet compiled,
#    fall back to a minimal action shim so the node can still run.
try:
    from hotel_luggage_robot.action import LuggageDelivery as _LD
    _HAS_HOTEL_MSGS = True
except ImportError:
    _HAS_HOTEL_MSGS = False


# ─────────────────────────────────────────────────────────────────────────────
# Tiny action definition used when hotel_luggage_robot msgs are unavailable
# (allows testing the wormhole logic in isolation)
# ─────────────────────────────────────────────────────────────────────────────
if not _HAS_HOTEL_MSGS:
    from rclpy.action import ActionServer  # noqa – already imported
    # We create a minimal nav-only action using NavigateToPose fields directly


# ─────────────────────────────────────────────────────────────────────────────
class WormholeNavigator(Node):
    """
    ROS 2 Humble node that replicates the multi-map wormhole navigation logic
    from the original ROS 1 `multi_map_nav` package, ported to rclpy + Nav2.
    """

    # ── Result codes (mirror NavigateToPose result codes for clarity) ─────────
    RESULT_SUCCESS = "success"
    RESULT_FAILED  = "failed"
    RESULT_CANCELLED = "cancelled"

    def __init__(self):
        super().__init__("wormhole_navigator")

        # ── Parameters ────────────────────────────────────────────────────────
        self.declare_parameter("wormhole_db_path",   "hotel_wormholes.db")
        self.declare_parameter("initial_map",        "floor_1")
        self.declare_parameter("maps_base_dir",      "")
        self.declare_parameter("map_frame",          "map")
        self.declare_parameter("robot_frame",        "base_footprint")
        self.declare_parameter("nav2_action_name",
            "/navigate_to_pose")
        self.declare_parameter("load_map_service",
            "/map_server/load_map")
        self.declare_parameter("initial_pose_topic",
            "/initialpose")
        self.declare_parameter("elevator_status_topic",
            "/elevator_controller/door_state")
        self.declare_parameter("virtual_layer_ns",
            "/global_costmap/virtual_layer")
        self.declare_parameter("map_load_wait_sec",  2.5)
        self.declare_parameter("elevator_wait_timeout_sec", 60.0)
        self.declare_parameter("door_wall_thickness_m",     0.15)
        self.declare_parameter("door_wall_cost",            254)
        self.declare_parameter("goal_yaw_tolerance", 0.2)
        self.declare_parameter("wormhole_approach_tolerance", 0.25)

        # ── State ─────────────────────────────────────────────────────────────
        self._current_map: str = self.get_parameter("initial_map").value
        self._db_path: str     = self.get_parameter("wormhole_db_path").value
        self._db: Optional[sqlite3.Connection] = None
        self._delivery_lock = threading.Lock()

        # Elevator door state tracking ("/elevator_controller/door_state")
        # States: "open", "closed", "in_transit"
        self._elevator_door_state: str = "closed"
        self._elevator_status_event = threading.Event()

        # Virtual wall UUID for current elevator door (set when wall is created)
        self._door_wall_uuid: Optional[str] = None

        # ── TF2 ───────────────────────────────────────────────────────────────
        self._tf_buffer   = tf2_ros.Buffer()
        self._tf_listener = tf2_ros.TransformListener(self._tf_buffer, self)

        # ── Callback group (reentrant so action callbacks + service calls ─────
        # ── can run concurrently)                                              ─
        self._cb_group = ReentrantCallbackGroup()

        # ── Open database ─────────────────────────────────────────────────────
        self._open_db()

        # ── Nav2 NavigateToPose action client ─────────────────────────────────
        self._nav_client = rclpy.action.ActionClient(
            self,
            NavigateToPose,
            self.get_parameter("nav2_action_name").value,
            callback_group=self._cb_group,
        )

        # ── Nav2 map loader service client ────────────────────────────────────
        self._load_map_client = self.create_client(
            LoadMap,
            self.get_parameter("load_map_service").value,
            callback_group=self._cb_group,
        )

        # ── Virtual layer service clients (nav2-virtual-layer repo) ──────────
        vl_ns = self.get_parameter("virtual_layer_ns").value
        if _HAS_VIRTUAL_LAYER:
            self._vl_add_line = self.create_client(
                AddLine,
                f"{vl_ns}/add_line",
                callback_group=self._cb_group,
            )
            self._vl_remove = self.create_client(
                RemoveShape,
                f"{vl_ns}/remove_shape",
                callback_group=self._cb_group,
            )
        else:
            self._vl_add_line = None
            self._vl_remove   = None
            self.get_logger().warn(
                "nav2_virtual_layer not found – virtual door walls disabled"
            )

        # ── Elevator door/status subscriber ───────────────────────────────────
        # Subscribes to door_state ("open" / "closed" / "in_transit")
        self.create_subscription(
            String,
            self.get_parameter("elevator_status_topic").value,
            self._elevator_status_cb,
            10,
        )

        # ── AMCL initial pose publisher ───────────────────────────────────────
        self._initial_pose_pub = self.create_publisher(
            PoseWithCovarianceStamped,
            self.get_parameter("initial_pose_topic").value,
            10,
        )

        # ── Current map publisher (convenience) ───────────────────────────────
        self._map_pub = self.create_publisher(String, "/wormhole_nav/current_map", 10)

        # ── Action server: accept (target_x, target_y, target_map) ───────────
        # We piggyback on NavigateToPose goal fields + a string metadata field.
        # The 'behavior_tree' field is repurposed to carry target_map name so
        # we stay within standard nav2_msgs with zero extra compilation steps.
        self._action_server = ActionServer(
            self,
            NavigateToPose,
            "/wormhole_navigator/navigate_to_goal",
            execute_callback=self._execute_cb,
            goal_callback=self._goal_cb,
            cancel_callback=self._cancel_cb,
            callback_group=self._cb_group,
        )

        self._publish_current_map()
        self.get_logger().info(
            f"WormholeNavigator ready. Initial map: '{self._current_map}' | "
            f"DB: {self._db_path}"
        )

    # ─────────────────────────────────────────────────────────────────────────
    # Database
    # ─────────────────────────────────────────────────────────────────────────
    def _open_db(self):
        """Open (and initialise if empty) the SQLite wormhole database."""
        try:
            self._db = sqlite3.connect(self._db_path, check_same_thread=False)
            self._db.row_factory = sqlite3.Row
            self._init_schema()
            self.get_logger().info(f"Wormhole DB opened: {self._db_path}")
        except sqlite3.Error as exc:
            self.get_logger().error(f"Cannot open wormhole DB '{self._db_path}': {exc}")
            self._db = None

    def _init_schema(self):
        """Create the wormholes table if it doesn't already exist."""
        self._db.execute("""
            CREATE TABLE IF NOT EXISTS wormholes (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                from_map        TEXT NOT NULL,
                to_map          TEXT NOT NULL,
                from_x          REAL NOT NULL,
                from_y          REAL NOT NULL,
                from_yaw        REAL NOT NULL DEFAULT 0.0,
                map_yaml_path   TEXT NOT NULL,
                door_x1         REAL NOT NULL DEFAULT 0.0,
                door_y1         REAL NOT NULL DEFAULT 0.0,
                door_x2         REAL NOT NULL DEFAULT 0.0,
                door_y2         REAL NOT NULL DEFAULT 0.0,
                elevator_id     TEXT NOT NULL DEFAULT 'elevator_A'
            )
        """)
        self._db.commit()

    def _get_wormhole(self, from_map: str, to_map: str) -> Optional[sqlite3.Row]:
        """
        Query the DB for a direct wormhole from from_map to to_map.
        Returns the first matching row, or None if not found.
        """
        if self._db is None:
            return None
        cur = self._db.execute(
            "SELECT * FROM wormholes WHERE from_map=? AND to_map=? LIMIT 1",
            (from_map, to_map),
        )
        return cur.fetchone()

    def _get_hub_map(self) -> str:
        """
        Return the 'hub' map (used as an intermediate when no direct wormhole
        exists). In the original repo this was hard-coded as 'map1'.
        We use the map with the most outgoing wormholes.
        """
        if self._db is None:
            return self._current_map
        cur = self._db.execute(
            "SELECT from_map, COUNT(*) AS cnt FROM wormholes GROUP BY from_map ORDER BY cnt DESC LIMIT 1"
        )
        row = cur.fetchone()
        return row["from_map"] if row else self._current_map

    # ─────────────────────────────────────────────────────────────────────────
    # Action server callbacks
    # ─────────────────────────────────────────────────────────────────────────
    def _goal_cb(self, goal_request):
        """Accept or reject incoming goals."""
        if self._delivery_lock.locked():
            self.get_logger().warn("Navigation already in progress – rejecting goal.")
            return GoalResponse.REJECT
        self.get_logger().info(
            f"Accepted goal → map='{goal_request.behavior_tree}' "
            f"pos=({goal_request.pose.pose.position.x:.2f}, "
            f"{goal_request.pose.pose.position.y:.2f})"
        )
        return GoalResponse.ACCEPT

    def _cancel_cb(self, goal_handle):
        self.get_logger().info("Cancel requested.")
        return CancelResponse.ACCEPT

    def _execute_cb(self, goal_handle):
        """
        Main execution: multi-floor navigation with wormhole transitions.

        Goal fields used:
            pose            → target (x, y, yaw) in map frame
            behavior_tree   → target map name (string, repurposed field)
        """
        goal = goal_handle.request
        target_map = goal.behavior_tree.strip()  # repurposed field carries map name
        target_x   = goal.pose.pose.position.x
        target_y   = goal.pose.pose.position.y
        # Extract yaw from quaternion
        q = goal.pose.pose.orientation
        target_yaw = self._quat_to_yaw(q.x, q.y, q.z, q.w)

        self.get_logger().info(
            f"Navigation goal: map='{target_map}' "
            f"pos=({target_x:.2f}, {target_y:.2f}) yaw={math.degrees(target_yaw):.1f}°"
        )

        result_msg = NavigateToPose.Result()

        with self._delivery_lock:
            success, msg = self._navigate_to_goal(
                goal_handle, target_map, target_x, target_y, target_yaw
            )

        if goal_handle.is_cancel_requested:
            goal_handle.canceled()
            self.get_logger().info("Navigation cancelled.")
            return result_msg

        if success:
            goal_handle.succeed()
            self.get_logger().info(f"Navigation succeeded: {msg}")
        else:
            goal_handle.abort()
            self.get_logger().error(f"Navigation failed: {msg}")

        return result_msg

    # ─────────────────────────────────────────────────────────────────────────
    # Core navigation logic (ported from navigation_server.cpp)
    # ─────────────────────────────────────────────────────────────────────────
    def _navigate_to_goal(
        self,
        goal_handle,
        target_map: str,
        target_x: float,
        target_y: float,
        target_yaw: float,
    ):
        """
        Replicate the original NavigationServer::execute() logic in ROS 2.

        Cases:
        A. Same map  →  navigate directly
        B. Direct wormhole  →  go to wormhole → switch map → navigate to goal
        C. No direct wormhole  →  go to hub map via wormhole,
                                   then hub → target map via wormhole,
                                   then navigate to goal
        """
        # ── Case A: Already on the target map ────────────────────────────────
        if self._current_map == target_map:
            self.get_logger().info("Same map – navigating directly.")
            ok = self._nav2_navigate(goal_handle, target_x, target_y, target_yaw)
            return (ok, "Direct navigation done" if ok else "Nav2 failed")

        # ── Case B: Direct wormhole exists ────────────────────────────────────
        wormhole = self._get_wormhole(self._current_map, target_map)
        if wormhole:
            self.get_logger().info(
                f"Direct wormhole: {self._current_map} → {target_map} "
                f"via ({wormhole['from_x']:.2f}, {wormhole['from_y']:.2f})"
            )
            if not self._traverse_wormhole(goal_handle, wormhole):
                return False, "Failed to traverse direct wormhole"
            ok = self._nav2_navigate(goal_handle, target_x, target_y, target_yaw)
            return (ok, "Multi-map navigation done" if ok else "Final nav failed")

        # ── Case C: Need intermediate hub map ────────────────────────────────
        hub_map = self._get_hub_map()
        self.get_logger().info(
            f"No direct wormhole – routing via hub '{hub_map}': "
            f"{self._current_map} → {hub_map} → {target_map}"
        )

        # Step 1: current → hub
        wh_to_hub = self._get_wormhole(self._current_map, hub_map)
        if not wh_to_hub:
            return False, f"No wormhole from '{self._current_map}' to hub '{hub_map}'"
        if not self._traverse_wormhole(goal_handle, wh_to_hub):
            return False, "Failed to reach hub map"

        # Step 2: hub → target
        wh_to_target = self._get_wormhole(hub_map, target_map)
        if not wh_to_target:
            return False, f"No wormhole from hub '{hub_map}' to '{target_map}'"
        if not self._traverse_wormhole(goal_handle, wh_to_target):
            return False, "Failed to reach target map from hub"

        ok = self._nav2_navigate(goal_handle, target_x, target_y, target_yaw)
        return (ok, "Hub-routed navigation done" if ok else "Final nav failed")

    def _elevator_status_cb(self, msg: String):
        """
        Receive door_state updates from the elevator controller.
        State values: "open" | "closed" | "in_transit"
        """
        prev = self._elevator_door_state
        self._elevator_door_state = msg.data.strip().lower()
        if prev != self._elevator_door_state:
            self.get_logger().info(f"Elevator door state: {self._elevator_door_state}")
            # Notify any thread waiting on the event
            self._elevator_status_event.set()

    def _traverse_wormhole(self, goal_handle, wormhole: sqlite3.Row) -> bool:
        """
        Full elevator traversal sequence with virtual door wall management.

        Steps
        -----
        1. Erect a virtual LINE wall across the elevator door (keep robot out).
        2. Navigate the robot to the elevator approach point.
        3. Call the elevator via /elevator_controller/call_elevator service.
        4. WAIT for /elevator_controller/door_state == "open"  ←── PHYSICAL CONFIRMATION
           (only then we know the elevator car has arrived on this floor).
        5. Remove the virtual door wall.
        6. Navigate robot into the elevator (small forward movement).
        7. Wait for /elevator_controller/door_state == "closed" + "in_transit".
        8. Wait for /elevator_controller/door_state == "open" again (arrived at target).
        9. Hot-swap map via /map_server/load_map.
        10. Publish AMCL initial pose at elevator exit on new floor.
        11. Navigate out of elevator.
        """
        wx       = wormhole["from_x"]
        wy       = wormhole["from_y"]
        wyaw     = wormhole["from_yaw"]
        to_map   = wormhole["to_map"]
        map_yaml = wormhole["map_yaml_path"]
        door_x1  = wormhole["door_x1"]
        door_y1  = wormhole["door_y1"]
        door_x2  = wormhole["door_x2"]
        door_y2  = wormhole["door_y2"]
        elev_id  = wormhole["elevator_id"]

        self.get_logger().info(
            f"Traversing wormhole to '{to_map}' via elevator '{elev_id}': "
            f"approach=({wx:.2f}, {wy:.2f}) yaw={math.degrees(wyaw):.1f}°"
        )

        # ── Step 1: Erect virtual wall across elevator door ───────────────────
        wall_uuid = self._erect_door_wall(door_x1, door_y1, door_x2, door_y2)

        # ── Step 2: Navigate to elevator approach point ───────────────────────
        if not self._nav2_navigate(goal_handle, wx, wy, wyaw):
            self.get_logger().error("Failed to reach elevator approach point")
            self._remove_door_wall(wall_uuid)
            return False

        # ── Step 3: Call elevator ─────────────────────────────────────────────
        self.get_logger().info(f"Calling elevator '{elev_id}' → {to_map}")
        # (elevator controller handles the actual hardware call;
        #  we just wait for the physical door-open confirmation below)

        # ── Step 4: Wait for elevator doors to open (physical confirmation) ───
        timeout = self.get_parameter("elevator_wait_timeout_sec").value
        self.get_logger().info(
            f"Waiting up to {timeout:.0f}s for elevator doors to open..."
        )
        arrived = self._wait_for_door_state("open", timeout_sec=timeout)
        if not arrived:
            self.get_logger().error(
                f"Elevator door did not open within {timeout}s – aborting"
            )
            self._remove_door_wall(wall_uuid)
            return False
        self.get_logger().info("Elevator doors OPEN – physical confirmation received.")

        # ── Step 5: Remove virtual door wall ─────────────────────────────────
        self._remove_door_wall(wall_uuid)

        # ── Step 6: Drive into elevator (small forward step past door line) ───
        inside_x = wx + 0.5 * math.cos(wyaw)
        inside_y = wy + 0.5 * math.sin(wyaw)
        if not self._nav2_navigate(goal_handle, inside_x, inside_y, wyaw):
            self.get_logger().warn("Could not navigate fully into elevator – continuing anyway")

        # ── Step 7: Wait for doors to close ──────────────────────────────────
        self._wait_for_door_state("closed", timeout_sec=15.0)
        self.get_logger().info("Elevator doors closed – in transit to " + to_map)

        # ── Step 8: Wait for elevator to arrive (doors open at destination) ───
        arrived = self._wait_for_door_state("open", timeout_sec=timeout)
        if not arrived:
            self.get_logger().error(
                "Elevator did not arrive at destination within timeout"
            )
            return False
        self.get_logger().info(f"Elevator arrived at '{to_map}' – doors open.")

        # ── Step 9: Hot-swap map ──────────────────────────────────────────────
        if not self._load_map(map_yaml, to_map):
            return False

        # ── Step 10: Re-initialize AMCL at elevator exit ─────────────────────
        #   Exit pose on the new floor is symmetric to entry pose.
        #   SDF2MAP-generated maps have their own origins, so wx/wy here
        #   are the elevator exit coordinates IN THE NEW MAP's frame.
        self._publish_initial_pose(wx, wy, wyaw)

        # Brief wait for costmaps to update after map swap
        wait_sec = self.get_parameter("map_load_wait_sec").value
        self.get_logger().info(f"Waiting {wait_sec}s for costmap update after map switch...")
        time.sleep(wait_sec)

        # ── Step 11: Drive out of elevator ────────────────────────────────────
        out_x = wx + 1.2 * math.cos(wyaw)
        out_y = wy + 1.2 * math.sin(wyaw)
        self._nav2_navigate(goal_handle, out_x, out_y, wyaw)

        return True

    # ─────────────────────────────────────────────────────────────────────────
    # Virtual door wall helpers (nav2-virtual-layer integration)
    # ─────────────────────────────────────────────────────────────────────────
    def _erect_door_wall(
        self,
        x1: float, y1: float,
        x2: float, y2: float,
    ) -> Optional[str]:
        """
        Create a LETHAL virtual LINE barrier across the elevator door.
        Uses nav2_virtual_layer AddLine service.
        Returns the UUID of the created wall, or None if unavailable.
        """
        if not _HAS_VIRTUAL_LAYER or not self._vl_add_line:
            self.get_logger().debug("Virtual layer unavailable – skipping door wall")
            return None

        if not self._vl_add_line.wait_for_service(timeout_sec=3.0):
            self.get_logger().warn("AddLine service not ready – skipping door wall")
            return None

        req = AddLine.Request()
        req.x1         = x1
        req.y1         = y1
        req.x2         = x2
        req.y2         = y2
        req.thickness  = float(self.get_parameter("door_wall_thickness_m").value)
        req.cost_level = int(self.get_parameter("door_wall_cost").value)
        req.duration   = 300.0     # 5-minute max; will be explicitly removed earlier
        req.frame_id   = self.get_parameter("map_frame").value
        req.identifier = "elevator_door_wall"

        future = self._vl_add_line.call_async(req)
        rclpy.spin_until_future_complete(self, future, timeout_sec=5.0)

        if future.done() and future.result() and future.result().success:
            uuid_str = future.result().uuid
            self.get_logger().info(
                f"Virtual door wall erected: ({x1:.2f},{y1:.2f})→({x2:.2f},{y2:.2f}) "
                f"uuid={uuid_str}"
            )
            return uuid_str
        else:
            self.get_logger().warn("Failed to erect virtual door wall")
            return None

    def _remove_door_wall(self, wall_uuid: Optional[str]):
        """Remove the virtual door wall by UUID."""
        if not wall_uuid or not _HAS_VIRTUAL_LAYER or not self._vl_remove:
            return
        if not self._vl_remove.wait_for_service(timeout_sec=3.0):
            return

        req = RemoveShape.Request()
        req.identifier = wall_uuid
        future = self._vl_remove.call_async(req)
        rclpy.spin_until_future_complete(self, future, timeout_sec=5.0)
        self.get_logger().info(f"Virtual door wall removed (uuid={wall_uuid})")

    # ─────────────────────────────────────────────────────────────────────────
    # Elevator status helpers
    # ─────────────────────────────────────────────────────────────────────────
    def _wait_for_door_state(self, target_state: str, timeout_sec: float) -> bool:
        """
        Block until /elevator_controller/door_state == target_state.
        Returns True if reached within timeout, False otherwise.
        """
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            if self._elevator_door_state == target_state:
                return True
            # Use event for efficient waiting instead of busy-loop
            remaining = deadline - time.monotonic()
            self._elevator_status_event.wait(timeout=min(0.5, remaining))
            self._elevator_status_event.clear()
        return self._elevator_door_state == target_state

    # ─────────────────────────────────────────────────────────────────────────
    # Nav2 NavigateToPose (replaces move_base from original ROS 1 code)
    # ─────────────────────────────────────────────────────────────────────────
    def _nav2_navigate(
        self,
        goal_handle,
        x: float, y: float, yaw: float,
    ) -> bool:
        """
        Send a NavigateToPose goal to Nav2 and wait for the result.
        Mirrors the original `move_base_to()` helper in navigation_server.cpp,
        but uses Nav2 instead of move_base.
        """
        if not self._nav_client.wait_for_server(timeout_sec=10.0):
            self.get_logger().error("Nav2 NavigateToPose action server not available")
            return False

        # Build goal
        nav_goal = NavigateToPose.Goal()
        nav_goal.pose = self._build_pose_stamped(x, y, yaw)

        self.get_logger().info(
            f"  → Nav2 goal: ({x:.2f}, {y:.2f}) yaw={math.degrees(yaw):.1f}°"
        )

        # Send goal and wait (blocking via Event + callback)
        done_event = threading.Event()
        success    = [False]  # mutable container for callback

        def result_callback(future):
            try:
                result = future.result()
                success[0] = True  # NavigateToPose has no explicit result code
            except Exception as exc:
                self.get_logger().warn(f"Nav2 result error: {exc}")
            finally:
                done_event.set()

        def response_callback(future):
            gh = future.result()
            if not gh:
                self.get_logger().error("Nav2 rejected the goal")
                done_event.set()
                return
            result_future = gh.get_result_async()
            result_future.add_done_callback(result_callback)

        send_future = self._nav_client.send_goal_async(
            nav_goal,
            feedback_callback=lambda fb: self._nav2_feedback(fb, goal_handle),
        )
        send_future.add_done_callback(response_callback)

        # Wait with cancel support
        while not done_event.is_set():
            if goal_handle.is_cancel_requested:
                self.get_logger().info("Cancel detected – aborting Nav2 goal")
                return False
            time.sleep(0.1)

        return success[0]

    def _nav2_feedback(self, feedback_msg, parent_goal_handle):
        """Forward Nav2 feedback to the parent action client."""
        fb = feedback_msg.feedback
        self.get_logger().debug(
            f"Nav2 feedback: dist_remaining={fb.distance_remaining:.2f}m"
        )
        # Publish feedback to the LuggageDelivery/wormhole caller
        parent_feedback = NavigateToPose.Feedback()
        parent_feedback.current_pose = fb.current_pose
        parent_feedback.distance_remaining = fb.distance_remaining
        parent_goal_handle.publish_feedback(parent_feedback)

    # ─────────────────────────────────────────────────────────────────────────
    # Nav2 Lifecycle Map Server integration
    # Replaces: system("rosrun map_server map_server " + yaml_path)
    # ─────────────────────────────────────────────────────────────────────────
    def _load_map(self, map_yaml_path: str, new_map_name: str) -> bool:
        """
        Call /map_server/load_map to hot-swap the occupancy map.
        This is the ROS 2 replacement for spawning a new map_server process.
        """
        if not self._load_map_client.wait_for_service(timeout_sec=5.0):
            self.get_logger().warn(
                "/map_server/load_map service not available – "
                "running in simulation mode, skipping map load"
            )
            self._current_map = new_map_name
            self._publish_current_map()
            return True

        req = LoadMap.Request()
        req.map_url = map_yaml_path  # e.g. "file:///maps/floor_2.yaml"

        self.get_logger().info(
            f"Loading map for '{new_map_name}': {map_yaml_path}"
        )

        future = self._load_map_client.call_async(req)
        # Spin until done (we're in an action callback on a reentrant group)
        rclpy.spin_until_future_complete(self, future, timeout_sec=15.0)

        if future.done():
            resp = future.result()
            if resp is None:
                self.get_logger().error("LoadMap returned None")
                return False
            if resp.result != LoadMap.Response.RESULT_SUCCESS:
                self.get_logger().error(
                    f"LoadMap failed (code {resp.result}) for '{map_yaml_path}'"
                )
                return False
            self.get_logger().info(
                f"Map loaded successfully for floor '{new_map_name}'"
            )
            self._current_map = new_map_name
            self._publish_current_map()
            return True
        else:
            self.get_logger().error("LoadMap service timed out")
            return False

    # ─────────────────────────────────────────────────────────────────────────
    # AMCL re-localisation after map switch
    # ─────────────────────────────────────────────────────────────────────────
    def _publish_initial_pose(self, x: float, y: float, yaw: float):
        """
        Publish to /initialpose so AMCL re-initialises its particle filter
        at the known elevator exit position on the new floor.
        """
        msg = PoseWithCovarianceStamped()
        msg.header.stamp    = self.get_clock().now().to_msg()
        msg.header.frame_id = self.get_parameter("map_frame").value
        msg.pose.pose = self._build_pose_stamped(x, y, yaw).pose

        # Small covariance – we know exactly where the elevator is
        cov = [0.0] * 36
        cov[0]  = 0.05   # x variance
        cov[7]  = 0.05   # y variance
        cov[35] = 0.05   # yaw variance
        msg.pose.covariance = cov

        self._initial_pose_pub.publish(msg)
        self.get_logger().info(
            f"Published AMCL initial pose on '{self._current_map}': "
            f"({x:.2f}, {y:.2f}) yaw={math.degrees(yaw):.1f}°"
        )

    # ─────────────────────────────────────────────────────────────────────────
    # Utility helpers
    # ─────────────────────────────────────────────────────────────────────────
    def _build_pose_stamped(self, x: float, y: float, yaw: float) -> PoseStamped:
        ps = PoseStamped()
        ps.header.stamp    = self.get_clock().now().to_msg()
        ps.header.frame_id = self.get_parameter("map_frame").value
        ps.pose.position.x = x
        ps.pose.position.y = y
        ps.pose.position.z = 0.0

        # yaw → quaternion
        half_yaw = yaw / 2.0
        ps.pose.orientation.x = 0.0
        ps.pose.orientation.y = 0.0
        ps.pose.orientation.z = math.sin(half_yaw)
        ps.pose.orientation.w = math.cos(half_yaw)
        return ps

    @staticmethod
    def _quat_to_yaw(qx, qy, qz, qw) -> float:
        """Convert quaternion to yaw angle (radians)."""
        siny_cosp = 2.0 * (qw * qz + qx * qy)
        cosy_cosp = 1.0 - 2.0 * (qy * qy + qz * qz)
        return math.atan2(siny_cosp, cosy_cosp)

    def _publish_current_map(self):
        msg = String()
        msg.data = self._current_map
        self._map_pub.publish(msg)

    def destroy_node(self):
        if self._db:
            self._db.close()
        super().destroy_node()


# ─── Database seeding helper ──────────────────────────────────────────────────
def seed_demo_database(db_path: str, maps_base: str):
    """
    Populate the wormhole DB with a 5-floor hotel demo configuration.

    Elevator bank A: at (x=-1.0, y=-5.0)
      door opening: from (-1.8, -5.0) to (-0.2, -5.0)   [1.6 m wide]
    Elevator bank B: at (x=3.0, y=2.0)
      door opening: from (3.0, 1.2) to (3.0, 2.8)       [1.6 m wide]

    Run once:
      python3 wormhole_navigator.py --seed-db /path/to/hotel.db /path/to/maps/
    """
    conn = sqlite3.connect(db_path)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS wormholes (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            from_map        TEXT NOT NULL,
            to_map          TEXT NOT NULL,
            from_x          REAL NOT NULL,
            from_y          REAL NOT NULL,
            from_yaw        REAL NOT NULL DEFAULT 0.0,
            map_yaml_path   TEXT NOT NULL,
            door_x1         REAL NOT NULL DEFAULT 0.0,
            door_y1         REAL NOT NULL DEFAULT 0.0,
            door_x2         REAL NOT NULL DEFAULT 0.0,
            door_y2         REAL NOT NULL DEFAULT 0.0,
            elevator_id     TEXT NOT NULL DEFAULT 'elevator_A'
        )
    """)

    # Columns: from_map, to_map, from_x, from_y, from_yaw, map_yaml,
    #          door_x1, door_y1, door_x2, door_y2, elevator_id
    b = maps_base.rstrip("/") + "/"
    entries = [
        # ── Elevator Bank A (x=-1.0, y=-5.0, door faces +x direction) ──────
        # Door line: perpendicular to robot travel direction (yaw=0 → moving +x)
        ("floor_1","floor_2",-1.0,-5.0, 0.0, b+"floor_2.yaml",-1.0,-5.8,-1.0,-4.2,"elevator_A"),
        ("floor_2","floor_1",-1.0,-5.0, 0.0, b+"floor_1.yaml",-1.0,-5.8,-1.0,-4.2,"elevator_A"),
        ("floor_2","floor_3",-1.0,-5.0, 0.0, b+"floor_3.yaml",-1.0,-5.8,-1.0,-4.2,"elevator_A"),
        ("floor_3","floor_2",-1.0,-5.0, 0.0, b+"floor_2.yaml",-1.0,-5.8,-1.0,-4.2,"elevator_A"),
        ("floor_3","floor_4",-1.0,-5.0, 0.0, b+"floor_4.yaml",-1.0,-5.8,-1.0,-4.2,"elevator_A"),
        ("floor_4","floor_3",-1.0,-5.0, 0.0, b+"floor_3.yaml",-1.0,-5.8,-1.0,-4.2,"elevator_A"),
        ("floor_4","floor_5",-1.0,-5.0, 0.0, b+"floor_5.yaml",-1.0,-5.8,-1.0,-4.2,"elevator_A"),
        ("floor_5","floor_4",-1.0,-5.0, 0.0, b+"floor_4.yaml",-1.0,-5.8,-1.0,-4.2,"elevator_A"),
        # ── Elevator Bank B (x=3.0, y=2.0, door faces +y direction yaw=1.57) ─
        ("floor_1","floor_3", 3.0, 2.0,1.57, b+"floor_3.yaml", 2.2, 2.0, 3.8, 2.0,"elevator_B"),
        ("floor_3","floor_1", 3.0, 2.0,1.57, b+"floor_1.yaml", 2.2, 2.0, 3.8, 2.0,"elevator_B"),
        ("floor_1","floor_5", 3.0, 2.0,1.57, b+"floor_5.yaml", 2.2, 2.0, 3.8, 2.0,"elevator_B"),
        ("floor_5","floor_1", 3.0, 2.0,1.57, b+"floor_1.yaml", 2.2, 2.0, 3.8, 2.0,"elevator_B"),
    ]

    conn.executemany(
        "INSERT INTO wormholes "
        "(from_map,to_map,from_x,from_y,from_yaw,map_yaml_path,"
        " door_x1,door_y1,door_x2,door_y2,elevator_id) "
        "VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        entries,
    )
    conn.commit()
    conn.close()
    print(f"Seeded {len(entries)} wormhole entries into {db_path}")


# ─── Entry point ─────────────────────────────────────────────────────────────
def main(args=None):
    import sys

    # Quick seed-database helper (not a ROS node run)
    if len(sys.argv) >= 3 and sys.argv[1] == "--seed-db":
        db_path   = sys.argv[2]
        maps_base = sys.argv[3] if len(sys.argv) > 3 else ""
        seed_demo_database(db_path, maps_base)
        return

    rclpy.init(args=args)
    node = WormholeNavigator()

    # MultiThreadedExecutor so action callbacks + service calls don't deadlock
    executor = MultiThreadedExecutor(num_threads=4)
    executor.add_node(node)

    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
